# Generated by Django 2.2.7 on 2019-11-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=55, verbose_name='Nombre del Medico')),
                ('apellido', models.CharField(max_length=55, verbose_name='Apellido del Medico')),
                ('tipDoc', models.CharField(max_length=10, verbose_name='Tipo de Documento')),
                ('nroDoc', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('horaIng', models.DateField()),
                ('horaSalida', models.DateField()),
                ('turnoMax', models.IntegerField()),
                ('sexo', models.CharField(max_length=10, verbose_name='Masculino/Femenino')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=55, verbose_name='Nombre del Medico')),
                ('apellido', models.CharField(max_length=55, verbose_name='Apellido del Medico')),
                ('tipDoc', models.CharField(max_length=10, verbose_name='Tipo de Documento')),
                ('nroDoc', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('sexo', models.CharField(max_length=10, verbose_name='Masculino/Femenino')),
                ('medico', models.ManyToManyField(to='historiaClinica.Medico')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
