# Generated by Django 2.2.7 on 2019-11-20 12:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0002_auto_20191120_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Categoria')),
                ('fechaCreacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='nroDoc',
            new_name='numeroDoc',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='tipDoc',
            new_name='tipoDoc',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nroDoc',
            new_name='numeroDoc',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='tipDoc',
            new_name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sexo',
        ),
        migrations.AddField(
            model_name='medico',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='medico',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='fechaCreacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha creacion'),
        ),
        migrations.AddField(
            model_name='medico',
            name='fechaNacimiento',
            field=models.DateField(null=True, verbose_name='Fecha nacimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fechaCreacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha creacion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(null=True, verbose_name='Fecha nacimiento'),
        ),
        migrations.AddField(
            model_name='turno',
            name='fechaCreacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('historial', ckeditor.fields.RichTextField(verbose_name='Historia Clinica')),
                ('fechaCreacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historiaClinica.Paciente')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='historiaClinica.Categoria'),
        ),
    ]
