# Generated by Django 2.2.7 on 2019-12-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0002_auto_20191204_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='obraSocial',
        ),
        migrations.AddField(
            model_name='paciente',
            name='obraSocial',
            field=models.ManyToManyField(blank=True, null=True, to='historiaClinica.ObraSocial'),
        ),
    ]
