# Generated by Django 2.2.7 on 2019-12-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0003_auto_20191204_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='categoria',
        ),
        migrations.AddField(
            model_name='medico',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='historiaClinica.Categoria'),
        ),
    ]
