# Generated by Django 2.2.7 on 2019-11-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0003_auto_20191120_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='horaIng',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='horaSalida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
