# Generated by Django 2.2.7 on 2019-12-09 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0004_auto_20191204_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de turno')),
                ('estado', models.BooleanField(default=False, verbose_name='Completo/Pendiente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historiaClinica.Medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historiaClinica.Paciente')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
