# Generated by Django 2.2.7 on 2019-11-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0004_auto_20191120_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='numeroDoc',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numeroDoc',
            field=models.CharField(max_length=8),
        ),
    ]
