# Generated by Django 2.2.7 on 2019-12-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0005_turnos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turnos',
        ),
    ]
