# Generated by Django 2.2.7 on 2019-11-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0006_auto_20191121_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='obraSocial',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='historiaClinica.ObraSocial'),
        ),
    ]
