# Generated by Django 2.2.7 on 2019-12-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0009_turno_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['-horario'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
    ]
