# Generated by Django 2.2.7 on 2019-11-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0009_auto_20191122_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.AlterField(
            model_name='medico',
            name='tipoDoc',
            field=models.ForeignKey(on_delete='CASCADE', to='historiaClinica.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipoDoc',
            field=models.ForeignKey(on_delete='CASCADE', to='historiaClinica.TipoDocumento'),
        ),
    ]
