# Generated by Django 2.2.7 on 2019-11-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0010_auto_20191122_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='tipoDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historiaClinica.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipoDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historiaClinica.TipoDocumento'),
        ),
    ]
