# Generated by Django 2.2.7 on 2019-12-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0010_auto_20191209_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['-fechaCreacion'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
