# Generated by Django 2.2.7 on 2019-11-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0011_auto_20191122_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='obraSocial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='historiaClinica.ObraSocial'),
        ),
    ]
