# Generated by Django 2.2.7 on 2019-11-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0012_auto_20191122_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='tipoDoc',
            field=models.CharField(max_length=12, verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipoDoc',
            field=models.CharField(max_length=12, verbose_name='Tipo Documento'),
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
    ]
