# Generated by Django 2.2.7 on 2019-11-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0013_auto_20191122_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='tipoDoc',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipoDoc',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Tipo Documento'),
        ),
    ]
