# Generated by Django 2.2.7 on 2019-11-22 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historiaClinica', '0014_auto_20191122_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='medico',
            name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tipoDoc',
        ),
        migrations.AddField(
            model_name='medico',
            name='tipoDocumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='historiaClinica.TipoDocumento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipoDocumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='historiaClinica.TipoDocumento'),
        ),
    ]
